FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy prisma schema
COPY prisma ./prisma
RUN npx prisma generate

# Expose port
EXPOSE 3000

# Set environment
ENV NODE_ENV development

# Start development server
CMD ["npm", "run", "dev"]
